  language: node_js
  node_js:
  - "11.10.1"
 cache:
   directories:
     - node_modules
deploy:
  provider: heroku
  api_key:
    secure: 3d1dcf89-2035-4fe9-b681-9ebad93b93bf
  app: shrouded-sierra-74421
  on:
    repo: anthonypagano/hopindex-client
env:
  - DATABASE_URL=mongodb://apagano76:76apagano@ds121282.mlab.com:21282/react-capstone
  - TEST_DATABASE_URL=mongodb://apagano76:76apagano@ds229878.mlab.com:29878/react-capstone-test